### ISSUE TITLE
CMake issues

### ISSUE THREAD

**Issue by tklengyel** [Bareflank/hypervisor#860] opened 2019-05-02 03:42 UTC
As of 6dc4866bc417c396b40cdf255f417adcda579596 I'm running into the following using the default compile instructions:

```
[ 21%] Performing configure step for 'bfruntime_x86_64-vmm-elf'
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM_NASM compiler identification is NASM version 2.12.01
-- Found assembler: /usr/bin/nasm
-- Configuring done
CMake Error at CMakeLists.txt:50 (add_library):
  Target "bfcrt" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:70 (add_library):
  Target "bfdso" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:78 (add_library):
  Target "bfpthread" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:89 (add_library):
  Target "bfsyscall" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:50 (add_library):
  Target "bfcrt" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:70 (add_library):
  Target "bfdso" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:78 (add_library):
  Target "bfpthread" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:89 (add_library):
  Target "bfsyscall" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/ssjtoma/workspace/bareflank/build/bfruntime/x86_64-vmm-elf/build
CMakeFiles/bfruntime_x86_64-vmm-elf.dir/build.make:108: recipe for target 'bfruntime/x86_64-vmm-elf/stamp/bfruntime_x86_64-vmm-elf-configure' failed
make[2]: *** [bfruntime/x86_64-vmm-elf/stamp/bfruntime_x86_64-vmm-elf-configure] Error 1
CMakeFiles/Makefile2:751: recipe for target 'CMakeFiles/bfruntime_x86_64-vmm-elf.dir/all' failed
make[1]: *** [CMakeFiles/bfruntime_x86_64-vmm-elf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JaredWright** [comment] 2019-05-02 14:28
This line looks suspect to me:

```
The C compiler identification is Clang 3.9.1
```

I'm not sure how CMake in your environment finds/reports the compiler version being used, but Clang 6+ is currently supported. Which version of CMake are you using, and which OS/distro? 

Also, did you start your build from a completely empty build directory? That error looks very familiar to me from a few commits back, so I'm wondering if there's something leftover in your build directory that is causing it.

As of this morning, 6dc4866bc417c396b40cdf255f417adcda579596 builds on my Ubuntu 18.04 environment using CMake 3.14.0 and the default build configuration. If you have any more information about your particular environment that might help me reproduce this, that would be helpful!

**Comment by tklengyel** [comment] 2019-05-02 14:32
This is on debian stretch using a clean build directory. With clang-6.0 and clang++-6.0 I get:
```
CMake Error at scripts/cmake/macros.cmake:975 (message):
  ENABLE_BUILD_USERSPACE is not supported with clang
Call Stack (most recent call first):
  scripts/cmake/validate.cmake:44 (invalid_config)
  CMakeLists.txt:199 (include)


CMake Error at scripts/cmake/macros.cmake:962 (message):
  Build validation failed
Call Stack (most recent call first):
  CMakeLists.txt:200 (validate_build)


-- Configuring incomplete, errors occurred!

**Comment by tklengyel** [comment] 2019-05-02 14:32
$ cmake --version
cmake version 3.13.2

**Comment by tklengyel** [comment] 2019-05-02 14:37
With `-DENABLE_BUILD_USERSPACE=OFF` I get
```
[ 52%] Performing bfruntime_x86_64-vmm-elf_cleanup step for 'bfruntime_x86_64-vmm-elf'
Scanning dependencies of target bfsyscall
Scanning dependencies of target bfpthread
Scanning dependencies of target bfcrt
Scanning dependencies of target bfdso
[ 10%] Building CXX object CMakeFiles/bfdso.dir/src/dso/dso.cpp.o
[ 20%] Building CXX object CMakeFiles/bfcrt.dir/src/crt/crt.cpp.o
[ 30%] Building CXX object CMakeFiles/bfsyscall.dir/src/syscall/syscall.cpp.o
error: invalid value 'c++17' in '-std=c++17'
[ 40%] Building CXX object CMakeFiles/bfpthread.dir/src/pthread/pthread.cpp.o
CMakeFiles/bfdso.dir/build.make:62: recipe for target 'CMakeFiles/bfdso.dir/src/dso/dso.cpp.o' failed
make[5]: *** [CMakeFiles/bfdso.dir/src/dso/dso.cpp.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/bfdso.dir/all' failed
make[4]: *** [CMakeFiles/bfdso.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 50%] Building ASM_NASM object CMakeFiles/bfpthread.dir/src/pthread/threadcontext.asm.o
error: invalid value 'c++17' in '-std=c++17'error: error: 
invalid invalid valuevalue  'c++17''c++17' in  in '-std=c++17''-std=c++17'

CMakeFiles/bfsyscall.dir/build.make:62: recipe for target 'CMakeFiles/bfsyscall.dir/src/syscall/syscall.cpp.o' failed

**Comment by JaredWright** [comment] 2019-05-02 15:10
Thanks for the info! Here's a couple things I can think of for you to try:

It looks like CMake is trying to use a version of clang to compile the VMM that doesn't have c++17 support enabled. When you specified a version of clang to use, did you do it using a command line configuration like ```-DCMAKE_C_COMPILER=clang-6```? That will set the compiler for building userspace tools, but the vmm compiler is defined through a [separate toolchain file](https://github.com/Bareflank/hypervisor/blob/master/scripts/cmake/toolchain/clang_x86_64_vmm.cmake) in Bareflank's build system

Instead, try setting an environment variable ```CLANG_BIN``` to see if that helps. Maybe the VMM toolchain file is finding clang 3.9.1 in your environment first, and trying to use that to compile the VMM

**Comment by tklengyel** [comment] 2019-05-02 15:21
I've set them manually via the environment variables
```
export CC=clang-6.0
export CXX=clang-6.0
```

I've removed all other clang packages from the system, new `build` folder, now it's back to the same error:

```
[ 33%] Performing configure step for 'bfruntime_x86_64-vmm-elf'
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM_NASM compiler identification is NASM version 2.12.01
-- Found assembler: /usr/bin/nasm
-- Configuring done
CMake Error at CMakeLists.txt:50 (add_library):
  Target "bfcrt" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:70 (add_library):
  Target "bfdso" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:78 (add_library):
  Target "bfpthread" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:89 (add_library):
  Target "bfsyscall" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:50 (add_library):
  Target "bfcrt" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:70 (add_library):
  Target "bfdso" links to target "vmm::bfroot" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:78 (add_library):
  Target "bfpthread" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:89 (add_library):
  Target "bfsyscall" links to target "vmm::bfroot" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/ssjtoma/workspace/bareflank/build/bfruntime/x86_64-vmm-elf/build
CMakeFiles/bfruntime_x86_64-vmm-elf.dir/build.make:108: recipe for target 'bfruntime/x86_64-vmm-elf/stamp/bfruntime_x86_64-vmm-elf-configure' failed
make[2]: *** [bfruntime/x86_64-vmm-elf/stamp/bfruntime_x86_64-vmm-elf-configure] Error 1
CMakeFiles/Makefile2:1324: recipe for target 'CMakeFiles/bfruntime_x86_64-vmm-elf.dir/all' failed
make[1]: *** [CMakeFiles/bfruntime_x86_64-vmm-elf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JaredWright** [comment] 2019-05-02 15:37
Getting closer... 

Could you post the output of ```ls <path/to/your/build/dir>/export```?

**Comment by tklengyel** [comment] 2019-05-02 15:39
```
drt@l1:~/workspace/bareflank/build$ ls -la export/
total 12
drwxr-xr-x  2 drt drt 4096 May  2 09:20 .
drwxr-xr-x 18 drt drt 4096 May  2 09:19 ..
-rw-r--r--  1 drt drt 1181 May  2 09:20 bfruntime-vmm-config.cmake
-rw-r--r--  1 drt drt    0 May  2 09:17 pkg.list

**Comment by JaredWright** [comment] 2019-05-02 15:43
Just to make sure as well, you aren't trying to build an extension? The above output is just from building the base hypervisor project, right?

I just built using your exact version of CMake and clang on my environment  (Ubuntu 18.04), and it worked. I may have to spin up a Debian environment later today to investigate further... Could be a Debain specific thing?

**Comment by tklengyel** [comment] 2019-05-02 15:47
Right now I'm just trying to build the default vmm with default settings

```
git clone https://github.com/bareflank/hypervisor.git
mkdir build; cd build
cmake ../hypervisor
make
```

Ideally once this works I can move the LibVMI extension over to the latest master

**Comment by tklengyel** [comment] 2019-05-02 15:49
Interestingly on Ubuntu the same thing does work `¯\_(ツ)_/¯`. At least on ubuntu 18.10 after I had to compile cmake from scratch and fix up the clang paths with symlinks

**Comment by JaredWright** [comment] 2019-05-02 15:55
Huh... good to know. With all of this hassle you had to go through in mind, would it be useful to you if we updated our Vagrant support to provide an easily accessible and sane build environment? 

Our Vagrantfile is currently out of date (doesn't have the right version of CMake), but thats something we should be able to work out very quickly.

**Comment by connojd** [comment] 2019-05-02 15:56
Ah jeez I can't believe this hasn't cropped up yet.. Change line 117 to

   ```add_subproject(bfruntime vmm DEPENDS gsl libcxx bfroot)```

**Comment by tklengyel** [comment] 2019-05-02 15:59
> Ah jeez I can't believe this hasn't cropped up yet.. Change line 117 in the top CMakeLists.txt to
> `add_subproject(bfruntime vmm DEPENDS gsl libcxx bfroot)`

Ding ding! We have a winner :) It begs the question though... why does it work on Ubuntu without this?

**Comment by connojd** [comment] 2019-05-02 16:00
The variation is coming from how the actual jobs are being scheduled. Without the explicit dependency on bfroot, cmake is able to make bfruntime without waiting for bfroot.

**Comment by JaredWright** [comment] 2019-05-02 17:10
Alright, the fix for this is merged. Thanks for letting us know about this issue @tklengyel!

**Closed** 2019-05-02 17:10 UTC
