### ISSUE TITLE
[QUESTION]: Compilation errors on Windows

### ISSUE THREAD

**Issue by welovenoscoping** [Bareflank/hypervisor#708] opened 2018-08-16 04:03 UTC
Hi, I'm trying to compile on Windows but I am getting error code 1 from "cmd.exe". Compiling using g++ on cygwin worked fine, but I want to research on Windows.

Build steps I used:
1.) C:\Bareflank>git clone https://github.com/Bareflank/hypervisor
2.) cmake -G "Visual Studio 15 2017 Win64" -DENABLE_BUILD_VMM=OFF -DENABLE_BUILD_USERSPACE=OFF -DENABLE_BUILD_TEST=ON ../hypervisor
3.) msbuild hypervisor.sln

```
I'm using mbuild from this directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64

Build FAILED.

"C:\Bareflank\build_msbuild\hypervisor.sln" (default target) (1) ->
"C:\Bareflank\build_msbuild\bfm_x86_64-test-pe.vcxproj.metaproj" (default target) (3) ->
"C:\Bareflank\build_msbuild\bfsdk_x86_64-test-pe.vcxproj.metaproj" (default target) (4) ->
"C:\Bareflank\build_msbuild\bfsdk_x86_64-test-pe.vcxproj" (default target) (13) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Bareflan
k\build_msbuild\bfsdk_x86_64-test-pe.vcxproj]

    0 Warning(s)
    1 Error(s)
```

Any help is appreciated, thanks.

**Comment by rianquinn** [comment] 2018-08-16 14:47
A couple of notes:

- I built the hypervisor from master using both Cygwin and Visual Studio, and both work fine after a small patch (which was not the issue you were seeing). 
- The instructions on how to build on Windows can be found on the README.md. You have to follow them exactly, otherwise, it will not work. 
- Although we support building the unit tests for Bareflank using Visual Studio, if you actually want to run the hypervisor, you will need Cygwin, as we currently rely on Newlib which only compiles with a full Bash environment. This is a limitation we hope to have resolved in the future, but it will take some time to get there as we will have to rewrite the entire build system for Newlib to make it work. 
- As for why you were unable to build the unit tests using Visual Studio, I'm not really sure what the issue is there. The instructions for how to do that can be seen in our AppVeyor script which runs all the time without issue, so we know it works. The log you provided doesn't really say much, so I would need to see more and have a better idea of what you did to set up your Windows dev environment. 

IMO, go to the README.md and install a fresh version of Visual Studio and Cygwin, build using the instructions and let us know if you still have any issues. We would be happy to help out in any way possible. 

- Rian

**Comment by rianquinn** [comment] 2018-08-17 13:51
I'm going to close this for now. Let us know if you have any further issues.

**Closed by rianquinn** 2018-08-17 13:51 UTC
Labels: question
