### ISSUE TITLE
EPT synchronization

### ISSUE THREAD

**Issue by mmisono** [Bareflank/hypervisor#867] opened 2019-06-24 07:12 UTC
I have a question. [The hook example](https://github.com/Bareflank/hypervisor/blob/74698efaf5afbbab5b3cec3d7eb358aaa699fb7b/examples/hook/userspace/hook.cpp#L41-L48) says

```
    // We don't do core synchronization in the hypervisor for modifying EPT
    // which means that its possible (unlikely) for a CPU race to occur. To
    // prevent this, we tell our application to only run on CPU 0. To remove
    // this, EPT would need to be set up on all cores, and modifications to
    // EPT would require core synchronization, while requires IPIs that are
    // trapped by the hypervisor and processed properly. This can be done
    // using the EAPIs (all of the APIs are available), but it would make the
    // example far more complicated.
```

Is this synchronization functionality (IPI mechanism) available?

**Comment by rianquinn** [comment] 2019-06-24 15:01
Great question. 

The short answer is, we do not provide this sort of API yet. This is a really hard thing to do without enabling external interrupt exiting, which is something we try to avoid as it has a huge performance hit on the system, and we have a lot of users who need the hypervisor to act as a No-Hype meaning VMExits only occur when specific conditions are hit (violations, introspection, etc...), so performance is important for this project. 

We have thought about how to implement this for over a year now, and there are no easy answers. We have even gone as far as working with Intel to inform them of this issue, as we really need the ability to enable external interrupt exiting at the interrupt granularity (similar to AMD). The short story is, the hypervisor has no means to VMCall itself on another core. Here are your options to emulate this:

- Easiest to implement, worst performance: Enable external interrupt existing. Set up a critical region (mutex lock), and set up a message for the other core, and then fire an IPI. This will generate a VMExit that you can process. The downside to this is every single interrupt, including ticks, will generate a VMExit. Once you enable external interrupt exiting, you will also need to queue and inject all interrupts, which we have a set of integration tests that demonstrate this. This should be really easy to do with what we already support, you just have to be ok with the performance hit. Picking the vector that you IPI with either requires that you create a fake PCI device to reserve an interrupt via a kernel driver, or you can just pick one and cross your fingers (depends on your use-case). 
- Easy to implement, best performance, some lag: From userspace, VMCall to tell the hypervisor you want to do something (in the hook example, this would be to install the hook). Then, from userspace, switch to all of the other cores (we provide affinity APIs to do that), and VMCall to tell the hypervisor to wait. Note that when you switch to the other core you will have to do this in different threads to ensure you can cause all of the cores to wait at the same time. Once your primary core is complete, it can signal via a conditional variable that it can return. This should be trivial to implement and will work without issue, you just have to be ok with the lag that this would produce, and this only works when userspace initiates the request (oddly, this is the case usually). 
- Hard to implement, best performance, no lag: Leverage NMIs instead of external interrupts. We have tested this and it works (you can safely inject an NMI). The problem is, OS's like Linux use NMIs for thermal throttling. You would either need to convince the OS to stop doing this, or you would need to reprogram the APIC to use an external interrupt instead so that you can use NMIs for IPIs. There are a number of ways to do this, but the right way would be to write a driver for a fake PCI device that reserves a vector from the OS. You would then reprogram the APIC to use this vector for thermal throttling. Just make sure you ensure priority is the same (thermal throttling should be capable of injecting with the highest priority, and then when you get the interrupt, you would inject an NMI so that queuing is not needed). This way, whenever you see an NMI you can safely assume it is an IPI to the hypervisor. 

We have looked into other ways of doing this, likely using exceptions or other forms of exits, but in general, this seems to be the only way to handle this safely. IMO, option 2 should be your approach unless you have a specific reason for needing option 1 or option 3.

**Comment by mmisono** [comment] 2019-06-25 02:17
Thank you very much for the quick and detailed explanation.

As of option 3, how about using global variables to distinguish whether NMI is IPI to the hypervisor or not? i.e., 
- The primary core
   1. Initialize two global variables to zero
         a. "IPI flag" variable, which indicates NMI is IPI to the hypervisor
         b. "completed" variable, which shows the number of cores completed the IPI task
   2. Write 1 to "IPI flag" and then send NMI
   3. Wait until "completed" become the number of application cores
   4. Write "0" to the "IPI flag" variable
- Other cores
  1. Receive NMI
  2. In the NMI handler or NMI VMEXIT handler, check "IPI flag" variable
  3. if this value is "1", then
       a. perform IPI task
       b. increment "completed" variable
       c. Wait until the "IPI flag" becomes 0
  4. Otherwise, queue NMI for NMI injection to the guest
  5. Return from the handler

btw, I'm not sure if the VMM should call iret when receiving NMI during VMX non-root operations 
 (consequently, NMI VMEXIT occur) and not performing NMI injection to the guest.

**Comment by rianquinn** [comment] 2019-06-25 13:50
The problem is, if you get the NMI in the NMI handler and not as a VMExit, you would be executing inside the VMM without the ability to guard critical regions. This is fine if all you have to do is execute a TLB flush for example, but if you need to operate on something inside the VMM like a data structure, there is no safe way to do this. 

One option would be to enable the monitor trap flag in the NMI handler which would generate a VMExit on the next instruction. From there, you could do whatever you want. To do that, we would need to ensure that the bit setting logic in bfbitmanip.h were converted to atomic operations (something that we need to do anyways), and the logic you describe above would also have to use std::atomic. If you did that something like that, I think the above would work without the need to emulate NMIs.

**Comment by rianquinn** [comment] 2019-06-25 13:52
The only issue with the MTF, now that I think about it more, is the core might be in an idle state, which means you would need to wait for the idle state to complete. One way around this would be to set both the MTF and the Interrupt Window. Either one would be forced to exit within a single instruction, or right away.

**Comment by rianquinn** [comment] 2019-06-25 14:16
Uhg.... no.... atomic operations in bfbitmaip will not work because it still requires a read/write to the VMCS which is the problem. However... what might work, which is a little weird, but it would work well I think, would be to do something that would generate a VM entry failure. This would cause a VMExit when the resume occurred, and from there you could do what you needed to. 

This would actually address the issue we already have with the NMI handler as well. All the NMI handler would have to do is flip a bit, and if a VM entry failure is seen, check that bit, and if it were set, you would exit the NMI VMExit handler. Then you would do the logic above as needed, and the base could have a fix for the current race that already exists in the NMI handler (the we just ignore right now). 

The only question is... how to generate the entry failiure. I was thinking we could clear the VMCS without changing the lanched flag but that would race with Boxy when an actual clear is being performed. We might be able to corrupt the VMCS in some way by touching a register in the VMCS that the VMM would never touch, but I will have to look at the manual to see. My gut says we might be able to just provide a corrupt ID in the VMCS. 

Huh... I like where this is headed. This might provide use with the generic API we have been searching for.

**Comment by mmisono** [comment] 2019-06-26 00:17
hmm, the approach is interesting.

Could you tell me when NMI is blocked and unblocked during VMX operation if you know about it? The SDM says, "While an NMI interrupt handler is executing, the processor blocks delivery of subsequent NMIs until the next execution of the IRET instruction." (3A 6.7.1) The SDM also says, "If the “NMI exiting” VM-execution control is 1, IRET does not affect blocking of NMIs." (3A 25.3) So my question is when and who unblock NMI when receiving NMI during VMX non-root operation. I'm wondering if there is a possibility to receive another NMI in the NMI VMEXIT handler.

**Comment by rianquinn** [comment] 2019-06-26 12:26
The answer is yes.... you could receive an NMI while you are in the NMI VMExit Handler. There is no way to block and NMI. The only interrupts that can be masked are external interrupts, but as I said above, there is no granular way to trap on a single interrupt vector so you either trap on them all or none. With the protocol that I listed above for the base NMI functionality, an atomic count would be enough to handle that case. WRT to an IPI message, the API would simply have to ensure that the shared region could only be used 1:1, which would be enough to handle that as well. 

There is the case where a real NMI is fired while you are processing an IPI, but in that case, it's really not that complicated. The atomic count is increased in both, so if we see a message in the critical region, we know that at least one of the NMIs was due to the IPI. Even if the writing of the message and the NMIs race, you would still end up with the accounting working itself out, so I think it would work.

**Comment by rianquinn** [comment] 2019-06-27 15:26
We talked internally, and right now, this seems to be a simple way to get to the API set that we would like. I am going to close this for now as I think we are at a point in this discussion where testing is in order. Once I get the base using this approach, I will add a ticket for this that we can track on adding the IPI part of this.

**Closed by rianquinn** 2019-06-27 15:26 UTC
