### ISSUE TITLE
[Q] Locking/Pinning pages

### ISSUE THREAD

**Issue by Randshot** [Bareflank/hypervisor#463] opened 2017-06-28 20:47 UTC
Hi,
is there currently a way to prevent pages from being swapped out aside from simply disabling Paging in Windows?
For now I don't have any issues with simply disabling paging but I curious whether such a function is built into Bareflank (eapis).

**Comment by rianquinn** [comment] 2017-06-29 02:45
No, in general, a hypervisor doesn't really have that kind of control over the OS. Why specifically do you want to disable page swapping?

**Comment by Randshot** [comment] 2017-06-29 07:19
I am asking because I happen to get some of my split pages swapped out.

**Comment by nick-kvmhv** [comment] 2017-06-29 16:12
To pin the pages in the guest OS you have several options:
1) You can involve driver layer in pinning them. From there you can do it via kernel API. This is something I won't be able to reproduce in my KVM-based solution due to the lack of the driver layer. 
2) You can inject some guest code and invoke it from your VMCALL. I don't remember seeing anything related to this in Bareflank, but in theory it should be possible if you manage to somehow allocate a chunk of memory in guest kernel and copy your code there.
3) You can figure out how your guest OS manages pinning and apply the necessary changes from the hypervisor.

**Comment by rianquinn** [comment] 2017-07-14 12:00
@Randshot closing this for now. I can always reopen it if you have more questions.

**Closed by rianquinn** 2017-07-14 12:00 UTC
Labels: question
