### ISSUE TITLE
[RFC] Nested Virtualization

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#231] opened 2016-09-30 16:08 UTC
Please note that this is an RFC for version 1.2, which we have not started yet, but I wanted a single place to have open conversations about nested virtualization support. 

Specifically, in version 1.2, we plan to add nested virtualization support, and we have someone who is working on prototyping this right now, so I figured as questions are asked, everyone can help answer questions, and see where this is going. At a minimum, I would a like to support
- Bareflank L0, SimpleVisor L1
- Bareflank L0, Bareflank L1

With stretch goals for:
- Bareflank L0, Hyper-V L1
- Bareflank L0, VMWare Workstation
- Bareflank L0, HyperPlatform L1

Also note that the bulk of the logic for this will reside in the Extended APIs repo, and not this repo, but most of the RFCs for the Extended APIs will likely reside here to keep things in one place. To start, I would prefer the implementation to be non participating, meaning L0 and L1 cannot talk. This will likely cause performance issues until we can support VMCS Shadowing, but that's fine as this should be more academic to start. 

Finally, this is something I would love to see added to SimpleVisor and HyperPlatform at some point as well, so I see the task of figuring out how this "should" work as a group effort here. 

@brendank310, @ktemkin, @josephsharkey, @ionescu007, @tandasat

**Comment by rianquinn** [comment] 2016-09-30 16:11
Here is one of the emails I have had with Kelvin who is working this as reference, please correct me if I have something wrong or backwards here:

-------------

The VMXON region is only used by VMXON. The VMCS region is used by the rest of the instructions. It Maps out like this:

L0:
VMXON0     // the only VMXON region that is actually used by hardware
VMCS01      // the VMCS region created by L0 for L1 
VMCS02      // the VMCS region created by L0 for L2 (when L1 creates VMCS12)

L1:
VMXON1      // the VMXON region created by L1, it’s likely not needed, but L1 has to create it because it thinks it’s on real hardware
VMCS12       // the VMCS region created by L1 for L2 

When L0 makes VMX calls, they are delivered to the actual hardware. When L1 makes VMX calls they trap to L0 and it has to emulate them. If L1 calls VMXON, the VMXON1 address needs to be decoded from the VMExit info. All other VMX instructions made by L1 provide the VMCS12 address that also has to be decoded. Read / writes to VMCS12 by L1 get filtered and sent to VMCS02, and when L1 runs vmlaunch on VMCS12, L0 launches VMCS02 instead. 

At least that is my understanding, the manual will have more info on this. Specifically, Chapter 27, which says the following (might not be a bad idea to take a look at how KVM handles this to get a code example on how to do the math here):

For INVEPT, INVPCID, INVVPID, LGDT, LIDT, LLDT, LTR, SGDT, SIDT, SLDT, STR, VMCLEAR, VMPTRLD, VMPTRST, VMREAD, VMWRITE, VMXON, XRSTORS, and XSAVES, the exit qualification receives the value of the instruction’s displacement field, which is sign-extended to 64 bits if necessary (32 bits on processors that do not support Intel 64 architecture). If the instruction has no displacement (for example, has a register operand), zero is stored into the exit qualification.

On processors that support Intel 64 architecture, an exception is made for RIP-relative addressing (used only in 64-bit mode). Such addressing causes an instruction to use an address that is the sum of the displacement field and the value of RIP that references the following instruction. In this case, the exit qualification is loaded with the sum of the displacement field and the appropriate RIP value.

In all cases, bits of this field beyond the instruction’s address size are undefined. For example, suppose that the address-size field in the VM-exit instruction-information field (see Section 24.9.4 and Section 27.2.4) reports an n-bit address size. Then bits 63:n (bits 31:n on processors that do not support Intel 64 architecture) of the instruction displacement are undefined.

**Comment by KelvinHack1207** [comment] 2016-09-30 21:26
Hello everyone,  I am a Hong Kong people, and working in Tencent game security reseacrh and development department. 

And we are started a research about nested virtualization, for implementing security purpose.

And i should talk about my current progress.


For VT-x project:
I have extened DdiMon by tandasat for implementing a Ring-3 level memory hiding. Which is for protecting our Game.

And I have to go on with my progress. Nested virtualization, i had already implemented VMXON, VMCLEAR, VMPTRLD instruction with full emulation.

My next target is emulate a VMWRITE instruction.
My first thought is, when we trap into VMM caused by VMWRITE, we can capture a vmcs field and we assumed L1 is successfully execute Vmxon, vmclear, vmptrld, so that we know about physical address of Vmcs.

So for the Vmwrite emulation, can i implement it by new way, which is in vmwrite handler, we directly change the current vmcs to L1 provided that one by executing a Vmptrld instruction, and directly decode a vmcsfield , and call a vmwrite instruction in host (vmm) .


How about is my idea.please correct me if i something wrong.

- Kelvin

**Comment by rianquinn** [comment] 2016-09-30 23:48
When L1 performs a `vmwrite`, L0 should trap in the exit handler. You'll obviously have to perform all of the checks that regular hardware performs (like making sure a valid VMCS has been loaded, etc...), but assuming all is good L0 will need to write to VMCS02, which is the actual VMCS for L2. The same thing applies to `vmread` but in reverse. L0 will read from VMCS02, and return the result.

Most of the guest fields should be VMCS12 <-> VMCS02, but the host fields will likely be very different (i.e. the host fields should be for L0), so when L1 attempts to read a host field from VMCS12, you need to return the same thing that was written. 

To handle this I see two approaches. You can either load VMCS12 and write all of the guest / host fields using `vmwrite`, or you could maintain your own data structure to avoid the additional VMX instructions. The downside here is that your be using even more memory. 

Thoughts?

**Comment by KelvinHack1207** [comment] 2016-10-01 08:48
I have curious about what will be happened if we use vmptrld in VMWRITE handler?

After guest trap to the vmexit handler, The VMCS will be use ? 

Because, I think if we can use vmptrld and vmwrite in VMWRITE handler it will be sound great.

**Comment by rianquinn** [comment] 2016-10-01 13:17
If VMCS01 is loaded (i.e. host fields for L0, and guest fields for L1), then when you trap on a `vmwrite`, you can then (and IMO should), run `vmptrld` to load VMCS02 into hardware and then use `vmwrite` to write to it. You would then run `vmptrld` again to load VMCS01 and then `vmresume`

**Comment by ionescu007** [comment] 2016-10-01 15:22
I'm not sure this is actually correct. From my understanding, and also
seeing some implementations, there is only ever *one* true hardware VMCS,
and only one VM that ever gets launched -- L0.

When you emulate vmread/vmwrite, you do it into your own "fake" VMCS which
can have whichever format you'd like, as long as it supports all the fields
of the 'real' VMCS. You can see for example how KVM defined theirs. This
can be improved by using the new Skylake instructions that allow
not-needing to trap on vmwrite/vmread.

My understanding is that you never physically load anyone else's VMCS at
any time -- you simply emulate their exits and call their exit handler.


Best regards,
Alex Ionescu

**Comment by KelvinHack1207** [comment] 2016-10-01 16:02
Yes. Alex, your idea is good. And I am going to implement it .

But the one more detail question is, how do you think when we read/ write the vmcs which is saved when L1 execute vmptrld and trap into ourselves.

Should we use it, or ignore it create a custom structure and use it when Vmread and vmwrite

- Kelvin

**Comment by rianquinn** [comment] 2016-10-01 16:07
If VMCS01 is loaded and traps on a `vmwrite` to VMCS12, you will have to perform that `vmwrite` on VMCS02 (assuming it's a guest field, and it's been filtered / modified as needed), which will require a `vmptrld`. Since you are still in L0, this is still a real VMCS, so your right with respect that only VMCS0X structures should ever be loaded into real hardware. 

The only exception to this is how you plan to store that actual VMCS12 bits. If you do what KVM does and store this information yourself, its likely to be faster, and better organized, but it will use more memory than simply loading VMCS12 and performing the read / write. The only other advantage of read / writing to VMCS12 is if L1 attempts to manually read / write VMCS12, it will get valid data. 

That all being said, I would likely implement it the same way as KVM since manually reading / writing the VMCS is not supported by Intel, and Bareflank at least has easy access to `std::` data structures so storing this information on our end is pretty trivial.

**Comment by KelvinHack1207** [comment] 2016-10-01 16:50
Ok. Let go on my work with KVM did. ;)
But did you think any disadvantages of performing vmptrld and vmwrite directly on vmcs?

Thanks.

Kelvin

**Comment by KelvinHack1207** [comment] 2016-10-04 00:37
VMREAD / VMWRITE is good enough right now.

My next target is emulating a VMLAUNCH instruction.  after all state loading and control field,
should we modify a VMCS02's host RIP to our vmexit handler (L0) ?

A  bit confused on there.

- Kelvin

**Comment by rianquinn** [comment] 2016-10-04 00:56
Yes, all of the host fields will likely end up as the L0 fields instead of L1. That being said, the exit handler will also likely have to do different things based on whether it's L1 trapping or L2 trapping.

**Comment by KelvinHack1207** [comment] 2016-10-04 09:06
Nice. I try to emulate it first.

- Kelvin

**Comment by KelvinHack1207** [comment] 2016-10-04 09:21
How do you think, what is the better way to identify the VMexit is caused by L1/ or L2?

Kelvin

**Comment by KelvinHack1207** [comment] 2016-10-04 21:59
For my understanding, emulating VMLAUNCH : 
1. Check and fill the VMCS1-2 into VMCS0-2 except host field, 
2. Fill VMCS0-1 host state field into VMCS1-2, 
3. Finally, we launch a L2 

Thought of "Launch a L2" :

Should we load the VMCS0-2 into CPU by executing VMPTRLD, and directly execute VMLAUNCH in L0 for Launching L2  ?

Or we shouldn't lo load VMCS0-2 and launch the L2 by those instruction.  instead, we directly move the our RIP to L2 vmentry point (VMCS0-2's Guest rip) , and which means L2 is launched?

Which method are better?  or any other ideas?

**Comment by rianquinn** [comment] 2016-10-04 23:26
You should store a struct for user defined info for each VMCS (FS/GS is a good place to do that, but on the stack works too), and in the struct you can tell if you are trapping on L1 or L2.

And yes.. you should be loading VMCS02 into hardware. Since I have personally never done this, I'm not entirely sure if the host state fields are identical for VMCS02 and VMCS02, but that's where I would start.

**Comment by KelvinHack1207** [comment] 2016-10-07 11:28
Should i load the vmcs02 into hardware, and directly execute vmresume ?

And normally, it will go back to Guest Rip of vmcs02 which is L1 expected. Am i right?

Kelvin

**Comment by KelvinHack1207** [comment] 2016-10-07 11:33
If directly execute vmresume, cpu may reported the vmcs02 launch state is not "launched".

Or i should execute a vmlaunch once before vmresume to L2.

Kelvin

**Comment by rianquinn** [comment] 2016-10-07 12:54
If VMCS02 has never been launched before you should use VMLaunch, all other times you use VMResume. Guest RIP == L2 (i.e. VMCS0--2--). If you need to execute L1, you would use launch VMCS01.

**Comment by KelvinHack1207** [comment] 2016-10-07 14:57
if we run VMLAUNCH in L0's VMLAUNCH handler. which means will not return L2 by VMRESUME, but VMLAUNCH instead?

**Comment by rianquinn** [comment] 2016-10-07 15:03
normally you run `vmresume` in the exit handler because the exit handler is associated with the currently running VMCS that had to have been launched for the exit handler to execute in the first place. Since you are running a different VMCS, you need to launch first, then resume after that, so there has to be some bookkeeping for each VMCS to know if it has been launched or not.

**Comment by KelvinHack1207** [comment] 2016-10-07 16:52
But once I VMLAUNCH it, the RIP is directly move to VMCS02's Guest RIP, and never return. How can I resume after that?

**Comment by rianquinn** [comment] 2016-10-07 16:56
At some point VMCS02 will trap. For example, if a CPUID is executed, VMCS02 will trap to L0. Since L0 is not the hypervisor for VMCS02, L0 must `vmresume` L1 and forward the vm exit information so that L1 can handle the CPUID. Once L1 handles this and finally runs `vmresume` on VMCS12, you trap on `vmresume` and run `vmresume` on VMCS02 again, passing the information from L1 to L2. 

Hence you can see why nested virtualization has a performance impact 😄

**Comment by KelvinHack1207** [comment] 2016-10-07 17:14
So can i think when the L1 trapped into L0 by VMLAUNCH, that VMExit handler never call VMRESUME anymore ?

**Comment by rianquinn** [comment] 2016-10-07 17:16
If L1 runs `vmlaunch` on VMCS12 and VMCS02 has already been launched you need to `vmresume` to L1 with the appropriate error. If VMCS02 has never been launched before, you would run `vmlaunch`.

**Comment by KelvinHack1207** [comment] 2016-10-07 17:18
OK. Thanks . I try it. looks complicated :(

**Comment by rianquinn** [comment] 2016-10-07 17:19
It is... 😄 . And like I said before, I have not done this before, this is just what I have read, so there might be details here I am missing.

**Comment by KelvinHack1207** [comment] 2016-10-09 13:54
Finally can perform a VM-Entry emulation. And next step I would like to emulate a Vm-exit , and I have an idea similar to following flowchart, please correct me if i wrong, 
![mstn8h12 n_ymy93 p3y3](https://cloud.githubusercontent.com/assets/22551808/19220913/fde00a72-8e6a-11e6-9f31-b3c09e7d8ff6.png)

**Comment by rianquinn** [comment] 2016-10-09 14:02
The only thing I see here that doesn't make sense to me is... to my understanding you should never actually load VMCS12 into hardware.

**Comment by KelvinHack1207** [comment] 2016-10-09 14:05
you mean VMExit emulation part?

**Comment by KelvinHack1207** [comment] 2016-10-09 14:05
I'm not very sure how is better way for do that.

**Comment by rianquinn** [comment] 2016-10-09 14:08
So my understanding is, if a VMExit occurs to L0 you need to figure out which VMCS it came from, VMCS01, or VMCS02. If it came from VMCS01, you simply need to emulate the instruction as you normally would. If it came from VMCS02, you need to re-encode the exit information, and `vmresume` into L1 so that it can handle the exit until it run `vmresume` on VMCS12, in which case you would run `vmresume` on VMCS02.

**Comment by KelvinHack1207** [comment] 2016-10-09 14:14
1: For figure out which VMCS it came from, yes i think i need to think a good method for this.
2: After figured it out. I need to re-encode the exit information, but which VMCS should I fill in, in case VMExit came from VMCS02. I just simply think i can write into VMCS12 and load it into CPU and vmresume to L1

**Comment by KelvinHack1207** [comment] 2016-10-09 14:15
or it should be VMCS02

**Comment by rianquinn** [comment] 2016-10-09 14:19
If the exit is from VMCS02, you would re-encode the exit information in your own structures (like @ionescu007 was talking about), and then `vmresume` VMCS01, which will execute L1. L1 will then run `vmread` to get that exit information which will trap to you again, and you will emulate the `vmread` instruction and `vmresume` back to L1, and repeat this until L1 gets through the entire process of handling the exit for VMCS02 for you. Once it's done it will try to `vmresume` to VMCS12, in which case you `vmresume` VMCS02.

**Comment by KelvinHack1207** [comment] 2016-10-09 15:11
But how should we fill in the Guest rip field of Vmcs01 before we resume. Is it Vmcs01 guest rip equal to Vmcs12 host rip?(its vmexit handler)

**Comment by rianquinn** [comment] 2016-10-09 15:13
vmcs01::guest_rip == vmcs12::host_rip

**Comment by KelvinHack1207** [comment] 2016-10-09 15:18
Got it

**Comment by KelvinHack1207** [comment] 2016-10-12 08:41
Everythings is good right now. After L2 is launched, L2 successfully trapped by L0 and L0 can be able to L1 by modify its Guest Rip/Rsp. And the VMExit event parameter and reason can also be trasnfered to L1 vmexit handler.

Above of VMExit emulation is tested by executing INT 3 instruction in L2, after it launched.

The following flowchart is now what i did.

![fl8 aefkjihelqlul _e](https://cloud.githubusercontent.com/assets/22551808/19303290/a685d4dc-909a-11e6-9f50-889221e9a559.png)

Anything else am i missed? or I am wrong, please correct me if i'm wrong.

And the next step should be emulated a VMRESUME, let the L1 transfer control to L2.

- Kelvin

**Comment by KelvinHack1207** [comment] 2016-10-12 10:13
For vmresume emulation, I think i need to used VMCS02 again , and resume to next instruction of the instruction that caused VMExit. 

- Kelvin

**Comment by rianquinn** [comment] 2016-10-12 18:09
The flowchart you provided looks good minus a couple of small things:
- Like @ionescu007 said, you can write to VMCS12, but you don't have to. Since a `vmread` / `vmwrite` to VMCS12 from L1 is emulated by L0, you can store the contents of VMCS12 in your own structure in L0. In Bareflank we will likely use a hash table to do this as it would be a LOT faster than loading VMCS12, reading / writing, etc. It can be done that way, but you don't have to, and your likely going to see a performance increase using your own storage
- With respect to RIP/RSP for VMCS01, you don't need to re-write this on every VMExit. When L1 writes RIP / RSP to the host fields in VMCS12, you simply write the values to the guest fields in VMCS01. 

Other than that, it seems like your making great progress. Keep up the good work.

**Comment by KelvinHack1207** [comment] 2016-10-12 19:07
Yes. I am using hash too. For decoding the offset and directly read/write on my allocated memory page.

How about the vmresume part.  I dun even know why I vmresume to L2. Vm-Entry will not fail, but also the computer is hang without Bsod😂

Currently im write next instruction of the instruction which is trapped by L0 in Guest RIP of  vmcs02. And guest rsp didnt change. 

My understanding, after L2 is launched, any vmexit in the L2 is trapped by L0, and we change the vmcs01 and resume to L1 vmexit handler.( in case we need send to L1.) So that vmcs02 rsp is consistence, so it Rsp seem to be true after L1 resume to L2 in case resume by vmcs02

And other field of vmcs02 just same as vmlaunch that one.

- kelvin

**Comment by rianquinn** [comment] 2016-10-13 01:57
So yeah, not sure why you are seeing a hang, but in my experience that means your getting close (this kind of sh** always get's worse right before it just works). And yes, a trap from L2 should go to L0, and then you resume L1 to handle it.

**Comment by KelvinHack1207** [comment] 2016-10-13 08:06
Resume L1 has been done, but also after L1 handle, I execute VMRESUME again for resume to L2, that moment hang. This time resume by VMCS02, and modify it Guest Rip to next instruction of that caused VMExit Instruction.

But it is hang-over SOSAD.

**Comment by KelvinHack1207** [comment] 2016-10-13 14:11
I wrote Guest rip but after VMRESUME it get here, seem to be PAUSE Loop... i have no idea what is going on LoL... So that computer is hanging.

![7 2v r 3ylq6 y dpbbr2t](https://cloud.githubusercontent.com/assets/22551808/19352315/fda357e2-9191-11e6-9a28-2702c7905d66.png)

**Comment by ionescu007** [comment] 2016-10-15 11:30
Might help to load symbols.. looks like you're in the NT kernel? Maybe the
Idle Loop?

Best regards,
Alex Ionescu

**Comment by KelvinHack1207** [comment] 2016-10-15 15:08
Maybe. Still looking for reason.

**Comment by KelvinHack1207** [comment] 2016-10-15 15:14
I tried to add a breakpoint in L2 guest rip , so supposed it will be trapped by L0 again, but it didnt.

**Comment by KelvinHack1207** [comment] 2016-10-16 23:27
The reason is that,I forgot copy a read-only field to vmcs12 when trapped by vmcs02, then L1 cannot read it normally (e.g. Vm exit instruction lenght.).

And now fixed.

**Comment by rianquinn** [comment] 2016-10-16 23:29
Nice!!!

**Comment by KelvinHack1207** [comment] 2016-10-18 18:28
Thanks for your teach :-) just done my very very minor testing run hyper-platform within hyper-platform. AND nested a breakpoint exception(others' L0 directly return L2) temporarily IN single core environment. Everythings goes well now.  

![rguub u qujxci o4 x9 zp](https://cloud.githubusercontent.com/assets/22551808/19490920/a7ac9a2c-95a3-11e6-91c7-7473d6de6fe9.png)

**Comment by rianquinn** [comment] 2016-10-18 18:30
Ha that's awesome. Ok... so, whenever we test software, we use this: https://coveralls.io/builds/8393798/source?filename=bfvmm%2Fsrc%2Fvmcs%2Fsrc%2Fvmcs_intel_x64_check_host.cpp

You should post a picture of this playing with your nested hypervisor. 😄

**Comment by KelvinHack1207** [comment] 2016-10-18 18:42
lol.. what is the youtube video means, I will try to adding a nested code into a bareflank as a little distribute in this project.

**Comment by rianquinn** [comment] 2016-10-18 18:44
hahaha, I have a 4 year old daughter so you'll see a lot of pre-school references in the things I do.

**Comment by rianquinn** [comment] 2016-10-18 18:44
Oh... and I would love to see this done in Bareflank

**Comment by KelvinHack1207** [comment] 2016-10-18 18:48
lol.. so sudden and funny. 

Try my best, hyper-platform that one may not be very stable. Just complete about 4 hours lol..( complete means no hang and BSOD only :-( .. ) haha.

**Comment by ionescu007** [comment] 2016-10-18 21:18
Is your code available anywhere? I am currently working on SimpleVisor
within SimpleVisor, and my next step will be HyperPlatform under
SimpleVisor.

Best regards,
Alex Ionescu

**Comment by rianquinn** [comment] 2016-10-18 21:23
@ionescu007 Nice.... any plans for Bareflank under SimpleVisor ;)

**Comment by tandasat** [comment] 2016-10-18 21:32
Glad to hear that HyperPlatform is being used for this project as a test
target.

@KelvinHack1207 <https://github.com/KelvinHack1207> Brilliant work, really.
I will learn from your work a lot.


Best,
Satoshi

**Comment by KelvinHack1207** [comment] 2016-10-19 03:08
@ionescu007  I tidy up the code and post it soon.  since it is very bad coding style haaa. Just functionality test.

@tandasat  OMG. you are one of the teacher since i learn VT.  I learnt a lot from you :)

**Comment by Kelvinhack** [comment] 2016-10-19 17:18
https://github.com/Kelvinhack/kHypervisor

@ionescu007  Maybe it is not good at all. I will try to make it better

**Comment by Kelvinhack** [comment] 2016-10-20 13:15
I found a problem that on my code some applications uses WaitForSingleObject / WaitForMultipleObjects for waiting a events,  may cause their thread freezed until I off the VMM, the event will be set immediately, and the thread keep going. 

I can't think anythings related to event object in VT area, that will caused the thread freezed.

Kelvin

**Comment by rianquinn** [comment] 2016-11-08 16:00
@Kelvinhack Now that you have Nested Virtualization working can I close this? Once we start working on Bareflank's version of this, I will re-create a new feature request ticket to track our internal progress.

**Comment by Kelvinhack** [comment] 2016-11-08 16:45
Sure. Thanks you guys

**Closed** 2016-11-08 16:56 UTC
Labels: request for comments
