### ISSUE TITLE
[BUG]: remaining memory in VMM

### ISSUE THREAD

**Issue by carter-yagemann** [Bareflank/hypervisor#415] opened 2017-01-24 15:55 UTC
Is there a way to programmatically determine how much memory the VMM has remaining during runtime?

Sometimes things go wrong in my experiments and data backs up in the VMM resulting in a crash. It would be nice to be able to check the remaining memory so my code could react when the VMM is dangerously low on memory.

**Comment by rianquinn** [comment] 2017-01-24 16:03
@carter-yagemann 

There isn't at the moment, but it should not be too difficult to add a function to do that. Memory is managed here:
https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/memory_manager/mem_pool.h

Just loop through the bitmap and check for blocks marked as free. I should warn you that we have an outstanding task in version 1.2 to change to a SLAB allocator (similar to Linux and NOVA). Currently, the mem_pool that we have will fragment pretty bad if you do too many allocations / frees (a problem that was identified when strings were being used on every exit accidentally). a SLAB allocator is likely going to be the best approach for handling allocations constantly. If it ends up being a huge issue for now, you can increase memory in the VMM here:
https://github.com/Bareflank/hypervisor/blob/master/include/constants.h#L130

We should be rolling rc1.1.2 in the next couple of days. Once we get done with v1.1, I will be focusing on Bareflank instead of the hyperkernel, and will move up the priority of getting the SLAB allocator in there, and making sure that allocations don't cause issues. Let me know if there is anything else I can do to help. 

@ktemkin @connojd

**Comment by carter-yagemann** [comment] 2017-01-24 19:32
I noticed the definition is conditional: `#ifndef MAX_HEAP_POOL`. If I'm writing my code as a separate module for in-tree compilation, can I define this in my code without causing a redefine error?

**Comment by rianquinn** [comment] 2017-01-24 19:48
Yes, I made these conditional on purpose. The best way to do it is to set CC_FLAGS and CXX_FLAGS in the shell with "-DXXX". This way you can customize what you want without having to mod the code. For example, this is how I get serial to work with PCI serial cards as the port is 0xE000.. usually. 😄

**Comment by carter-yagemann** [comment] 2017-01-24 20:11
Makes sense, thanks!

**Comment by carter-yagemann** [comment] 2017-02-02 15:04
So if I have a separate project for in-tree compilation with bareflank (similar to the extended APIs examples), and I need to increase something like `MAX_MEM_MAP_POOL`, where exactly is the best place to put the definition? It seems that putting them in my project's makefiles doesn't propagate up (or I'm doing it wrong) and I'm trying to avoid having to manually edit `include/constants.h`.

Thanks

**Comment by rianquinn** [comment] 2017-02-02 15:06
add the following to your .bashrc

export CFLAGS=“-DMAX_MEM_MAP_MEMPOOL=<something>"
export CXXFLAGS=“-DMAX_MEM_MAP_MEMPOOL=<something>”

**Comment by carter-yagemann** [comment] 2017-02-02 15:45
I'm trying to think more from an end user's perspective cloning my project for research. Maybe I just throw the exports in a `env.sh` file. Or maybe this point is moot with the coming build system overhaul?

**Comment by rianquinn** [comment] 2017-02-02 16:19
I like the idea of the env.sh. We would have to add "--xxx" options to the configure script, but you would then be able to set memory sizes, turn on production mode, etc... I would agree that the issue is likely not important once we move to BitBake, so we will have to revisit this after we get the new build system put in place.

**Comment by rianquinn** [comment] 2017-02-10 18:39
@carter-yagemann now that the RFC is out for this, I'm going to close this ticket for now as we can manage this issue via the RFC while it's being worked:

https://github.com/Bareflank/hypervisor/issues/425

**Closed by rianquinn** 2017-02-10 18:39 UTC
Labels: bug
